apiVersion: v1
kind: Service
metadata:
  name: pipecd-demo
spec:
  selector:
    app: pipecd-demo    # Este selector enrutará el tráfico tanto a Primary como a Canary
  ports:
  - protocol: TCP
    port: 9085
    targetPort: 9085
